FROM tensorflow/tensorflow:2.18.0-gpu

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y parallel

RUN mkdir /app
WORKDIR /app
COPY ./requirements-tensorflow.txt /app

RUN pip install uv
RUN uv pip install -r requirements-tensorflow.txt --system
COPY . /app

CMD ["sh", "launch.sh"]